ARG BASE_IMAGE="ghcr.io/gbraad-devenv/ubi9-golang/dotfiles"
ARG BASE_VERSION="latest"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/ubi9-golang"

USER root

RUN systemctl enable tailscaled

ENTRYPOINT ["/sbin/init"]