ARG BASE_IMAGE="ghcr.io/gbraad-devenv/ubi/dotfiles"
ARG BASE_VERSION="9"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/ubi9-golang"

USER root

# delve golang golang-bin \
RUN INSTALL_PKGS="go-toolset" \
    && dnf install -y --setopt=tsflags=nodocs \
        $INSTALL_PKGS \
    && rpm -V $INSTALL_PKGS \
    && rm -rf /var/cache/yum
